# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.
#
options:
  debug:
    default: False
    description: Enable debug logging.
    type: boolean
  log-level:
    default: WARNING
    type: string
    description: Log level (WARNING, INFO, DEBUG, ERROR)

  admin-user:
    default: admin
    description: Default admin user for keystone
    type: string
  admin-role:
    default: Admin
    description: Admin role to be associated with admin and service users
    type: string
  service-tenant:
    default: services
    description: Name of tenant to associate with service credentials
    type: string

  service-port:
    default: 5000
    description: Port the public and internal endpoints will listen on
    type: int
  admin-port:
    default: 35357
    description: Port the admin endpoint will listen on
    type: int

  os-admin-hostname:
    default: keystone.juju
    description: |
      The hostname or address of the admin endpoints that should be advertised
      in the keystone identity provider.
    type: string
  os-internal-hostname:
    default: keystone.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the keystone identity provider.
    type: string
  os-public-hostname:
    default: keystone.juju
    description: |
      The hostname or address of the internal endpoints that should be advertised
      in the keystone identity provider.
    type: string
  region:
    default: RegionOne
    description: Space delimited list of OpenStack regions
    type: string

  fernet-max-active-keys:
    type: int
    default: 3
    description: |
      This is the maximum number of active keys. It has a minimum of 3, which includes the
      spare and staging keys. When set to 3, the rotation time for the keys is the same as
      the token expiration time. When set to a higher value, the rotation time is less than
      the `token-expiration` time as calculated by:

      rotation-time = token-expiration / (fernet-max-active-keys -2)

      Please see the charm documentation for further details about how to use the Fernet token
      parameters to achieve a key strategy appropriate for the system in question.
  token-expiration:
    type: int
    default: 3600
    description: Amount of time (in seconds) a token should remain valid.
  catalog-cache-expiration:
    type: int
    default: 60
    description: Amount of time (in seconds) the catalog should be cached for.
  dogpile-cache-expiration:
    type: int
    default: 60
    description: |
      Amount of time (in seconds) to cache items in the dogpile.cache. This only applies
      to cached methods that do not have an explicitly defined cache expiration time.

  identity-backend:
    type: string
    default: "sql"
    description: |
      Keystone identity backend, valid options are sql and pam

